// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ecocraft.Models;

#nullable disable

namespace ecocraft.Migrations
{
    [DbContext(typeof(EcoCraftDbContext))]
    [Migration("20260408_AddUniqueIndexUserServer")]
    partial class AddUniqueIndexUserServer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CraftingTablePluginModule", b =>
                {
                    b.Property<Guid>("CraftingTableId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PluginModuleId")
                        .HasColumnType("uuid");

                    b.HasKey("CraftingTableId", "PluginModuleId");

                    b.HasIndex("PluginModuleId");

                    b.ToTable("CraftingTablePluginModule");
                });

            modelBuilder.Entity("ItemTagAssoc", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("ItemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ItemTagAssoc");
                });

            modelBuilder.Entity("UserCraftingTablePluginModule", b =>
                {
                    b.Property<Guid>("UserCraftingTableId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PluginModuleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserCraftingTableId", "PluginModuleId");

                    b.HasIndex("PluginModuleId");

                    b.ToTable("UserCraftingTablePluginModule");
                });

            modelBuilder.Entity("ecocraft.Models.CraftingTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocalizedNameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocalizedNameId");

                    b.HasIndex("ServerId");

                    b.ToTable("CraftingTable", (string)null);
                });

            modelBuilder.Entity("ecocraft.Models.DataContext", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsShoppingList")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserServerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserServerId");

                    b.ToTable("DataContext", (string)null);
                });

            modelBuilder.Entity("ecocraft.Models.DynamicValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseValue")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("DynamicValue", (string)null);
                });

            modelBuilder.Entity("ecocraft.Models.Element", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("DefaultIsReintegrated")
                        .HasColumnType("boolean");

                    b.Property<decimal>("DefaultShare")
                        .HasColumnType("numeric");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<Guid>("ItemOrTagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuantityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItemOrTagId");

                    b.HasIndex("QuantityId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("SkillId");

                    b.ToTable("Element", (string)null);
                });

            modelBuilder.Entity("ecocraft.Models.ItemOrTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DefaultPrice")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsTag")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LocalizedNameId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocalizedNameId");

                    b.HasIndex("ServerId");

                    b.ToTable("ItemOrTag", (string)null);
                });

            modelBuilder.Entity("ecocraft.Models.LocalizedField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ar_sa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("cs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("da")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("de")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("el")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("en_US")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("es")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("hu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("it")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ja")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ko")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pt_BR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pt_PT")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ru")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("uk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("vi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("zh_Hans")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("LocalizedField", (string)null);
                });

            modelBuilder.Entity("ecocraft.Models.ModUploadHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IconsCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UploadDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("UserId");

                    b.ToTable("ModUploadHistory", (string)null);
                });

            modelBuilder.Entity("ecocraft.Models.Modifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DynamicType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DynamicValueId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TalentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DynamicValueId");

                    b.HasIndex("SkillId");

                    b.HasIndex("TalentId");

                    b.ToTable("Modifier", (string)null);
                });

            modelBuilder.Entity("ecocraft.Models.PluginModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocalizedNameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Percent")
                        .HasColumnType("numeric");

                    b.Property<int>("PluginType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("SkillPercent")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("LocalizedNameId");

                    b.HasIndex("ServerId");

                    b.HasIndex("SkillId");

                    b.ToTable("PluginModule", (string)null);
                });

            modelBuilder.Entity("ecocraft.Models.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CraftMinutesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CraftingTableId")
                        .HasColumnType("uuid");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBlueprint")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LaborId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocalizedNameId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<long>("SkillLevel")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CraftMinutesId");

                    b.HasIndex("CraftingTableId");

                    b.HasIndex("LaborId");

                    b.HasIndex("LocalizedNameId");

                    b.HasIndex("ServerId");

                    b.HasIndex("SkillId");

                    b.ToTable("Recipe", (string)null);
                });

            modelBuilder.Entity("ecocraft.Models.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApiKey")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EcoServerId")
                        .HasColumnType("text");

                    b.Property<bool>("HasVideoUploader")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastDataUploadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Server", (string)null);
                });

            modelBuilder.Entity("ecocraft.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<decimal[]>("LaborReducePercent")
                        .IsRequired()
                        .HasColumnType("numeric[]");

                    b.Property<Guid?>("LocalizedNameId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Profession")
                        .HasColumnType("text");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LocalizedNameId");

                    b.HasIndex("ServerId");

                    b.ToTable("Skill", (string)null);
                });

            modelBuilder.Entity("ecocraft.Models.Talent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LocalizedDescriptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocalizedNameId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.Property<string>("TalentGroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("LocalizedDescriptionId");

                    b.HasIndex("LocalizedNameId");

                    b.HasIndex("SkillId");

                    b.ToTable("Talent", (string)null);
                });

            modelBuilder.Entity("ecocraft.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanUploadMod")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SecretId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ShowHelp")
                        .HasColumnType("boolean");

                    b.Property<bool>("SuperAdmin")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("ecocraft.Models.UserCraftingTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CraftMinuteFee")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CraftingTableId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataContextId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PluginModuleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CraftingTableId");

                    b.HasIndex("DataContextId");

                    b.HasIndex("PluginModuleId");

                    b.ToTable("UserCraftingTable", (string)null);
                });

            modelBuilder.Entity("ecocraft.Models.UserElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataContextId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMarginPrice")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReintegrated")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Share")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserRecipeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DataContextId");

                    b.HasIndex("ElementId");

                    b.HasIndex("UserRecipeId");

                    b.ToTable("UserElement", (string)null);
                });

            modelBuilder.Entity("ecocraft.Models.UserMargin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataContextId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Margin")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DataContextId");

                    b.ToTable("UserMargin", (string)null);
                });

            modelBuilder.Entity("ecocraft.Models.UserPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataContextId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemOrTagId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("MarginPrice")
                        .HasColumnType("numeric");

                    b.Property<bool>("OverrideIsBought")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("PrimaryUserElementId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PrimaryUserPriceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserMarginId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DataContextId");

                    b.HasIndex("ItemOrTagId");

                    b.HasIndex("PrimaryUserElementId");

                    b.HasIndex("PrimaryUserPriceId");

                    b.HasIndex("UserMarginId");

                    b.ToTable("UserPrice", (string)null);
                });

            modelBuilder.Entity("ecocraft.Models.UserRecipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataContextId")
                        .HasColumnType("uuid");

                    b.Property<bool>("LockShare")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentUserRecipeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoundFactor")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DataContextId");

                    b.HasIndex("ParentUserRecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("UserRecipe", (string)null);
                });

            modelBuilder.Entity("ecocraft.Models.UserServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EcoUserId")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Pseudo")
                        .HasColumnType("text");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("UserId", "ServerId")
                        .IsUnique();

                    b.ToTable("UserServer", (string)null);
                });

            modelBuilder.Entity("ecocraft.Models.UserSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ApplyMarginBetweenSkills")
                        .HasColumnType("boolean");

                    b.Property<decimal>("CalorieCost")
                        .HasColumnType("numeric");

                    b.Property<Guid>("DataContextId")
                        .HasColumnType("uuid");

                    b.Property<bool>("DisplayNonSkilledRecipes")
                        .HasColumnType("boolean");

                    b.Property<int>("MarginType")
                        .HasColumnType("integer");

                    b.Property<bool>("OnlyLevelAccessibleRecipes")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DataContextId");

                    b.ToTable("UserSetting", (string)null);
                });

            modelBuilder.Entity("ecocraft.Models.UserSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataContextId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DataContextId");

                    b.HasIndex("SkillId");

                    b.ToTable("UserSkill", (string)null);
                });

            modelBuilder.Entity("ecocraft.Models.UserTalent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataContextId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("TalentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DataContextId");

                    b.HasIndex("TalentId");

                    b.ToTable("UserTalent", (string)null);
                });

            modelBuilder.Entity("CraftingTablePluginModule", b =>
                {
                    b.HasOne("ecocraft.Models.CraftingTable", null)
                        .WithMany()
                        .HasForeignKey("CraftingTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.PluginModule", null)
                        .WithMany()
                        .HasForeignKey("PluginModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ItemTagAssoc", b =>
                {
                    b.HasOne("ecocraft.Models.ItemOrTag", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.ItemOrTag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserCraftingTablePluginModule", b =>
                {
                    b.HasOne("ecocraft.Models.PluginModule", null)
                        .WithMany()
                        .HasForeignKey("PluginModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.UserCraftingTable", null)
                        .WithMany()
                        .HasForeignKey("UserCraftingTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ecocraft.Models.CraftingTable", b =>
                {
                    b.HasOne("ecocraft.Models.LocalizedField", "LocalizedName")
                        .WithMany("CraftingTables")
                        .HasForeignKey("LocalizedNameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ecocraft.Models.Server", "Server")
                        .WithMany("CraftingTables")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalizedName");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("ecocraft.Models.DataContext", b =>
                {
                    b.HasOne("ecocraft.Models.UserServer", "UserServer")
                        .WithMany("DataContexts")
                        .HasForeignKey("UserServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserServer");
                });

            modelBuilder.Entity("ecocraft.Models.DynamicValue", b =>
                {
                    b.HasOne("ecocraft.Models.Server", "Server")
                        .WithMany("DynamicValues")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("ecocraft.Models.Element", b =>
                {
                    b.HasOne("ecocraft.Models.ItemOrTag", "ItemOrTag")
                        .WithMany("Elements")
                        .HasForeignKey("ItemOrTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.DynamicValue", "Quantity")
                        .WithMany("QuantityElements")
                        .HasForeignKey("QuantityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.Recipe", "Recipe")
                        .WithMany("Elements")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId");

                    b.Navigation("ItemOrTag");

                    b.Navigation("Quantity");

                    b.Navigation("Recipe");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ecocraft.Models.ItemOrTag", b =>
                {
                    b.HasOne("ecocraft.Models.LocalizedField", "LocalizedName")
                        .WithMany("ItemOrTags")
                        .HasForeignKey("LocalizedNameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ecocraft.Models.Server", "Server")
                        .WithMany("ItemOrTags")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalizedName");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("ecocraft.Models.LocalizedField", b =>
                {
                    b.HasOne("ecocraft.Models.Server", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("ecocraft.Models.ModUploadHistory", b =>
                {
                    b.HasOne("ecocraft.Models.Server", "Server")
                        .WithMany("ModUploadHistories")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ecocraft.Models.User", "User")
                        .WithMany("ModUploadHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ecocraft.Models.Modifier", b =>
                {
                    b.HasOne("ecocraft.Models.DynamicValue", "DynamicValue")
                        .WithMany("Modifiers")
                        .HasForeignKey("DynamicValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.Skill", "Skill")
                        .WithMany("Modifiers")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ecocraft.Models.Talent", "Talent")
                        .WithMany("Modifiers")
                        .HasForeignKey("TalentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DynamicValue");

                    b.Navigation("Skill");

                    b.Navigation("Talent");
                });

            modelBuilder.Entity("ecocraft.Models.PluginModule", b =>
                {
                    b.HasOne("ecocraft.Models.LocalizedField", "LocalizedName")
                        .WithMany("PluginModules")
                        .HasForeignKey("LocalizedNameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ecocraft.Models.Server", "Server")
                        .WithMany("PluginModules")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.Skill", "Skill")
                        .WithMany("PluginModules")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("LocalizedName");

                    b.Navigation("Server");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ecocraft.Models.Recipe", b =>
                {
                    b.HasOne("ecocraft.Models.DynamicValue", "CraftMinutes")
                        .WithMany("CraftMinutesRecipes")
                        .HasForeignKey("CraftMinutesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.CraftingTable", "CraftingTable")
                        .WithMany("Recipes")
                        .HasForeignKey("CraftingTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.DynamicValue", "Labor")
                        .WithMany("LaborRecipes")
                        .HasForeignKey("LaborId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.LocalizedField", "LocalizedName")
                        .WithMany("Recipes")
                        .HasForeignKey("LocalizedNameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ecocraft.Models.Server", "Server")
                        .WithMany("Recipes")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.Skill", "Skill")
                        .WithMany("Recipes")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CraftMinutes");

                    b.Navigation("CraftingTable");

                    b.Navigation("Labor");

                    b.Navigation("LocalizedName");

                    b.Navigation("Server");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ecocraft.Models.Skill", b =>
                {
                    b.HasOne("ecocraft.Models.LocalizedField", "LocalizedName")
                        .WithMany("Skills")
                        .HasForeignKey("LocalizedNameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ecocraft.Models.Server", "Server")
                        .WithMany("Skills")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalizedName");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("ecocraft.Models.Talent", b =>
                {
                    b.HasOne("ecocraft.Models.LocalizedField", "LocalizedDescription")
                        .WithMany("TalentDescriptions")
                        .HasForeignKey("LocalizedDescriptionId");

                    b.HasOne("ecocraft.Models.LocalizedField", "LocalizedName")
                        .WithMany("Talents")
                        .HasForeignKey("LocalizedNameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ecocraft.Models.Skill", "Skill")
                        .WithMany("Talents")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalizedDescription");

                    b.Navigation("LocalizedName");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ecocraft.Models.UserCraftingTable", b =>
                {
                    b.HasOne("ecocraft.Models.CraftingTable", "CraftingTable")
                        .WithMany("UserCraftingTables")
                        .HasForeignKey("CraftingTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.DataContext", "DataContext")
                        .WithMany("UserCraftingTables")
                        .HasForeignKey("DataContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.PluginModule", "PluginModule")
                        .WithMany()
                        .HasForeignKey("PluginModuleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CraftingTable");

                    b.Navigation("DataContext");

                    b.Navigation("PluginModule");
                });

            modelBuilder.Entity("ecocraft.Models.UserElement", b =>
                {
                    b.HasOne("ecocraft.Models.DataContext", "DataContext")
                        .WithMany("UserElements")
                        .HasForeignKey("DataContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.Element", "Element")
                        .WithMany("UserElements")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.UserRecipe", "UserRecipe")
                        .WithMany("UserElements")
                        .HasForeignKey("UserRecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataContext");

                    b.Navigation("Element");

                    b.Navigation("UserRecipe");
                });

            modelBuilder.Entity("ecocraft.Models.UserMargin", b =>
                {
                    b.HasOne("ecocraft.Models.DataContext", "DataContext")
                        .WithMany("UserMargins")
                        .HasForeignKey("DataContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataContext");
                });

            modelBuilder.Entity("ecocraft.Models.UserPrice", b =>
                {
                    b.HasOne("ecocraft.Models.DataContext", "DataContext")
                        .WithMany("UserPrices")
                        .HasForeignKey("DataContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.ItemOrTag", "ItemOrTag")
                        .WithMany("UserPrices")
                        .HasForeignKey("ItemOrTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.UserElement", "PrimaryUserElement")
                        .WithMany("UserPricesPrimaryOf")
                        .HasForeignKey("PrimaryUserElementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ecocraft.Models.UserPrice", "PrimaryUserPrice")
                        .WithMany()
                        .HasForeignKey("PrimaryUserPriceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ecocraft.Models.UserMargin", "UserMargin")
                        .WithMany("UserPrices")
                        .HasForeignKey("UserMarginId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DataContext");

                    b.Navigation("ItemOrTag");

                    b.Navigation("PrimaryUserElement");

                    b.Navigation("PrimaryUserPrice");

                    b.Navigation("UserMargin");
                });

            modelBuilder.Entity("ecocraft.Models.UserRecipe", b =>
                {
                    b.HasOne("ecocraft.Models.DataContext", "DataContext")
                        .WithMany("UserRecipes")
                        .HasForeignKey("DataContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.UserRecipe", "ParentUserRecipe")
                        .WithMany("ChildrenUserRecipes")
                        .HasForeignKey("ParentUserRecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ecocraft.Models.Recipe", "Recipe")
                        .WithMany("UserRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataContext");

                    b.Navigation("ParentUserRecipe");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ecocraft.Models.UserServer", b =>
                {
                    b.HasOne("ecocraft.Models.Server", "Server")
                        .WithMany("UserServers")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.User", "User")
                        .WithMany("UserServers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ecocraft.Models.UserSetting", b =>
                {
                    b.HasOne("ecocraft.Models.DataContext", "DataContext")
                        .WithMany("UserSettings")
                        .HasForeignKey("DataContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataContext");
                });

            modelBuilder.Entity("ecocraft.Models.UserSkill", b =>
                {
                    b.HasOne("ecocraft.Models.DataContext", "DataContext")
                        .WithMany("UserSkills")
                        .HasForeignKey("DataContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DataContext");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ecocraft.Models.UserTalent", b =>
                {
                    b.HasOne("ecocraft.Models.DataContext", "DataContext")
                        .WithMany("UserTalents")
                        .HasForeignKey("DataContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ecocraft.Models.Talent", "Talent")
                        .WithMany("UserTalents")
                        .HasForeignKey("TalentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataContext");

                    b.Navigation("Talent");
                });

            modelBuilder.Entity("ecocraft.Models.CraftingTable", b =>
                {
                    b.Navigation("Recipes");

                    b.Navigation("UserCraftingTables");
                });

            modelBuilder.Entity("ecocraft.Models.DataContext", b =>
                {
                    b.Navigation("UserCraftingTables");

                    b.Navigation("UserElements");

                    b.Navigation("UserMargins");

                    b.Navigation("UserPrices");

                    b.Navigation("UserRecipes");

                    b.Navigation("UserSettings");

                    b.Navigation("UserSkills");

                    b.Navigation("UserTalents");
                });

            modelBuilder.Entity("ecocraft.Models.DynamicValue", b =>
                {
                    b.Navigation("CraftMinutesRecipes");

                    b.Navigation("LaborRecipes");

                    b.Navigation("Modifiers");

                    b.Navigation("QuantityElements");
                });

            modelBuilder.Entity("ecocraft.Models.Element", b =>
                {
                    b.Navigation("UserElements");
                });

            modelBuilder.Entity("ecocraft.Models.ItemOrTag", b =>
                {
                    b.Navigation("Elements");

                    b.Navigation("UserPrices");
                });

            modelBuilder.Entity("ecocraft.Models.LocalizedField", b =>
                {
                    b.Navigation("CraftingTables");

                    b.Navigation("ItemOrTags");

                    b.Navigation("PluginModules");

                    b.Navigation("Recipes");

                    b.Navigation("Skills");

                    b.Navigation("TalentDescriptions");

                    b.Navigation("Talents");
                });

            modelBuilder.Entity("ecocraft.Models.Recipe", b =>
                {
                    b.Navigation("Elements");

                    b.Navigation("UserRecipes");
                });

            modelBuilder.Entity("ecocraft.Models.Server", b =>
                {
                    b.Navigation("CraftingTables");

                    b.Navigation("DynamicValues");

                    b.Navigation("ItemOrTags");

                    b.Navigation("ModUploadHistories");

                    b.Navigation("PluginModules");

                    b.Navigation("Recipes");

                    b.Navigation("Skills");

                    b.Navigation("UserServers");
                });

            modelBuilder.Entity("ecocraft.Models.Skill", b =>
                {
                    b.Navigation("Modifiers");

                    b.Navigation("PluginModules");

                    b.Navigation("Recipes");

                    b.Navigation("Talents");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("ecocraft.Models.Talent", b =>
                {
                    b.Navigation("Modifiers");

                    b.Navigation("UserTalents");
                });

            modelBuilder.Entity("ecocraft.Models.User", b =>
                {
                    b.Navigation("ModUploadHistories");

                    b.Navigation("UserServers");
                });

            modelBuilder.Entity("ecocraft.Models.UserElement", b =>
                {
                    b.Navigation("UserPricesPrimaryOf");
                });

            modelBuilder.Entity("ecocraft.Models.UserMargin", b =>
                {
                    b.Navigation("UserPrices");
                });

            modelBuilder.Entity("ecocraft.Models.UserRecipe", b =>
                {
                    b.Navigation("ChildrenUserRecipes");

                    b.Navigation("UserElements");
                });

            modelBuilder.Entity("ecocraft.Models.UserServer", b =>
                {
                    b.Navigation("DataContexts");
                });
#pragma warning restore 612, 618
        }
    }
}
